function nabla_u_xi = nabla_u_xi(in1,L,H,W,xi,eta,zeta)
%NABLA_U_XI
%    NABLA_U_XI = NABLA_U_XI(IN1,L,H,W,XI,ETA,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jul-2026 17:05:32

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
u5 = in1(5,:);
u6 = in1(6,:);
u7 = in1(7,:);
u8 = in1(8,:);
u9 = in1(9,:);
u10 = in1(10,:);
u11 = in1(11,:);
u12 = in1(12,:);
u13 = in1(13,:);
u14 = in1(14,:);
u15 = in1(15,:);
u16 = in1(16,:);
u17 = in1(17,:);
u18 = in1(18,:);
u19 = in1(19,:);
u20 = in1(20,:);
u21 = in1(21,:);
u22 = in1(22,:);
u23 = in1(23,:);
u24 = in1(24,:);
u25 = in1(25,:);
u26 = in1(26,:);
u27 = in1(27,:);
t2 = xi+1.0;
t3 = xi.^2;
t4 = xi-1.0;
t5 = t3-1.0;
mt1 = [(t4.*u1)./2.0+(t2.*u19)./2.0+(u1.*xi)./2.0-u10.*xi.*2.0+(u19.*xi)./2.0+(W.*t4.*u7.*zeta)./4.0+(W.*t2.*u25.*zeta)./4.0+(W.*u7.*xi.*zeta)./4.0-W.*u16.*xi.*zeta+(W.*u25.*xi.*zeta)./4.0+(H.*eta.*t4.*u4)./4.0+(H.*eta.*t2.*u22)./4.0+(H.*eta.*u4.*xi)./4.0-H.*eta.*u13.*xi+(H.*eta.*u22.*xi)./4.0];
mt2 = [(t4.*u2)./2.0+(t2.*u20)./2.0+(u2.*xi)./2.0-u11.*xi.*2.0+(u20.*xi)./2.0+(W.*t4.*u8.*zeta)./4.0+(W.*t2.*u26.*zeta)./4.0+(W.*u8.*xi.*zeta)./4.0-W.*u17.*xi.*zeta+(W.*u26.*xi.*zeta)./4.0+(H.*eta.*t4.*u5)./4.0+(H.*eta.*t2.*u23)./4.0+(H.*eta.*u5.*xi)./4.0-H.*eta.*u14.*xi+(H.*eta.*u23.*xi)./4.0];
mt3 = [(t4.*u3)./2.0+(t2.*u21)./2.0+(u3.*xi)./2.0-u12.*xi.*2.0+(u21.*xi)./2.0+(W.*t4.*u9.*zeta)./4.0+(W.*t2.*u27.*zeta)./4.0+(W.*u9.*xi.*zeta)./4.0-W.*u18.*xi.*zeta+(W.*u27.*xi.*zeta)./4.0+(H.*eta.*t4.*u6)./4.0+(H.*eta.*t2.*u24)./4.0+(H.*eta.*u6.*xi)./4.0-H.*eta.*u15.*xi+(H.*eta.*u24.*xi)./4.0,H.*t5.*u13.*(-1.0./2.0)+(H.*t4.*u4.*xi)./4.0+(H.*t2.*u22.*xi)./4.0,H.*t5.*u14.*(-1.0./2.0)+(H.*t4.*u5.*xi)./4.0+(H.*t2.*u23.*xi)./4.0,H.*t5.*u15.*(-1.0./2.0)+(H.*t4.*u6.*xi)./4.0+(H.*t2.*u24.*xi)./4.0];
mt4 = [W.*t5.*u16.*(-1.0./2.0)+(W.*t4.*u7.*xi)./4.0+(W.*t2.*u25.*xi)./4.0,W.*t5.*u17.*(-1.0./2.0)+(W.*t4.*u8.*xi)./4.0+(W.*t2.*u26.*xi)./4.0,W.*t5.*u18.*(-1.0./2.0)+(W.*t4.*u9.*xi)./4.0+(W.*t2.*u27.*xi)./4.0];
nabla_u_xi = reshape([mt1,mt2,mt3,mt4],3,3);
end
