function F_xi = F_xi(in1,L,H,W,xi,eta,zeta)
%F_xi
%    F_xi = F_xi(IN1,L,H,W,XI,ETA,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jul-2026 17:07:36

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
q7 = in1(7,:);
q8 = in1(8,:);
q9 = in1(9,:);
q10 = in1(10,:);
q11 = in1(11,:);
q12 = in1(12,:);
q13 = in1(13,:);
q14 = in1(14,:);
q15 = in1(15,:);
q16 = in1(16,:);
q17 = in1(17,:);
q18 = in1(18,:);
q19 = in1(19,:);
q20 = in1(20,:);
q21 = in1(21,:);
q22 = in1(22,:);
q23 = in1(23,:);
q24 = in1(24,:);
q25 = in1(25,:);
q26 = in1(26,:);
q27 = in1(27,:);
q28 = in1(28,:);
q29 = in1(29,:);
q30 = in1(30,:);
q31 = in1(31,:);
q32 = in1(32,:);
q33 = in1(33,:);
q34 = in1(34,:);
q35 = in1(35,:);
q36 = in1(36,:);
t2 = xi+1.0;
t3 = xi.^2;
t4 = xi-1.0;
t5 = t3-1.0;
mt1 = [(q1.*t4)./2.0+(q25.*t2)./2.0+(q1.*xi)./2.0-q13.*xi.*2.0+(q25.*xi)./2.0+(W.*q7.*t4.*zeta)./4.0+(W.*q31.*t2.*zeta)./4.0+(W.*q7.*xi.*zeta)./4.0-W.*q19.*xi.*zeta+(W.*q31.*xi.*zeta)./4.0+(H.*eta.*q4.*t4)./4.0+(H.*eta.*q28.*t2)./4.0+(H.*eta.*q4.*xi)./4.0-H.*eta.*q16.*xi+(H.*eta.*q28.*xi)./4.0+(H.*W.*eta.*q10.*t4.*zeta)./8.0+(H.*W.*eta.*q34.*t2.*zeta)./8.0+(H.*W.*eta.*q10.*xi.*zeta)./8.0-(H.*W.*eta.*q22.*xi.*zeta)./2.0+(H.*W.*eta.*q34.*xi.*zeta)./8.0];
mt2 = [(q2.*t4)./2.0+(q26.*t2)./2.0+(q2.*xi)./2.0-q14.*xi.*2.0+(q26.*xi)./2.0+(W.*q8.*t4.*zeta)./4.0+(W.*q32.*t2.*zeta)./4.0+(W.*q8.*xi.*zeta)./4.0-W.*q20.*xi.*zeta+(W.*q32.*xi.*zeta)./4.0+(H.*eta.*q5.*t4)./4.0+(H.*eta.*q29.*t2)./4.0+(H.*eta.*q5.*xi)./4.0-H.*eta.*q17.*xi+(H.*eta.*q29.*xi)./4.0+(H.*W.*eta.*q11.*t4.*zeta)./8.0+(H.*W.*eta.*q35.*t2.*zeta)./8.0+(H.*W.*eta.*q11.*xi.*zeta)./8.0-(H.*W.*eta.*q23.*xi.*zeta)./2.0+(H.*W.*eta.*q35.*xi.*zeta)./8.0];
mt3 = [(q3.*t4)./2.0+(q27.*t2)./2.0+(q3.*xi)./2.0-q15.*xi.*2.0+(q27.*xi)./2.0+(W.*q9.*t4.*zeta)./4.0+(W.*q33.*t2.*zeta)./4.0+(W.*q9.*xi.*zeta)./4.0-W.*q21.*xi.*zeta+(W.*q33.*xi.*zeta)./4.0+(H.*eta.*q6.*t4)./4.0+(H.*eta.*q30.*t2)./4.0+(H.*eta.*q6.*xi)./4.0-H.*eta.*q18.*xi+(H.*eta.*q30.*xi)./4.0+(H.*W.*eta.*q12.*t4.*zeta)./8.0+(H.*W.*eta.*q36.*t2.*zeta)./8.0+(H.*W.*eta.*q12.*xi.*zeta)./8.0-(H.*W.*eta.*q24.*xi.*zeta)./2.0+(H.*W.*eta.*q36.*xi.*zeta)./8.0];
mt4 = [H.*q16.*t5.*(-1.0./2.0)+(H.*q4.*t4.*xi)./4.0+(H.*q28.*t2.*xi)./4.0-(H.*W.*q22.*t5.*zeta)./4.0+(H.*W.*q10.*t4.*xi.*zeta)./8.0+(H.*W.*q34.*t2.*xi.*zeta)./8.0,H.*q17.*t5.*(-1.0./2.0)+(H.*q5.*t4.*xi)./4.0+(H.*q29.*t2.*xi)./4.0-(H.*W.*q23.*t5.*zeta)./4.0+(H.*W.*q11.*t4.*xi.*zeta)./8.0+(H.*W.*q35.*t2.*xi.*zeta)./8.0,H.*q18.*t5.*(-1.0./2.0)+(H.*q6.*t4.*xi)./4.0+(H.*q30.*t2.*xi)./4.0-(H.*W.*q24.*t5.*zeta)./4.0+(H.*W.*q12.*t4.*xi.*zeta)./8.0+(H.*W.*q36.*t2.*xi.*zeta)./8.0];
mt5 = [W.*q19.*t5.*(-1.0./2.0)+(W.*q7.*t4.*xi)./4.0+(W.*q31.*t2.*xi)./4.0-(H.*W.*eta.*q22.*t5)./4.0+(H.*W.*eta.*q10.*t4.*xi)./8.0+(H.*W.*eta.*q34.*t2.*xi)./8.0,W.*q20.*t5.*(-1.0./2.0)+(W.*q8.*t4.*xi)./4.0+(W.*q32.*t2.*xi)./4.0-(H.*W.*eta.*q23.*t5)./4.0+(H.*W.*eta.*q11.*t4.*xi)./8.0+(H.*W.*eta.*q35.*t2.*xi)./8.0,W.*q21.*t5.*(-1.0./2.0)+(W.*q9.*t4.*xi)./4.0+(W.*q33.*t2.*xi)./4.0-(H.*W.*eta.*q24.*t5)./4.0+(H.*W.*eta.*q12.*t4.*xi)./8.0+(H.*W.*eta.*q36.*t2.*xi)./8.0];
F_xi = reshape([mt1,mt2,mt3,mt4,mt5],3,3);
end
