function nabla_u_xi = nabla_u_xi(in1,L,H,W,xi,eta,zeta)
%NABLA_U_XI
%    NABLA_U_XI = NABLA_U_XI(IN1,L,H,W,XI,ETA,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jul-2026 17:07:36

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
u5 = in1(5,:);
u6 = in1(6,:);
u7 = in1(7,:);
u8 = in1(8,:);
u9 = in1(9,:);
u10 = in1(10,:);
u11 = in1(11,:);
u12 = in1(12,:);
u13 = in1(13,:);
u14 = in1(14,:);
u15 = in1(15,:);
u16 = in1(16,:);
u17 = in1(17,:);
u18 = in1(18,:);
u19 = in1(19,:);
u20 = in1(20,:);
u21 = in1(21,:);
u22 = in1(22,:);
u23 = in1(23,:);
u24 = in1(24,:);
u25 = in1(25,:);
u26 = in1(26,:);
u27 = in1(27,:);
u28 = in1(28,:);
u29 = in1(29,:);
u30 = in1(30,:);
u31 = in1(31,:);
u32 = in1(32,:);
u33 = in1(33,:);
u34 = in1(34,:);
u35 = in1(35,:);
u36 = in1(36,:);
t2 = xi+1.0;
t3 = xi.^2;
t4 = xi-1.0;
t5 = t3-1.0;
mt1 = [(t4.*u1)./2.0+(t2.*u25)./2.0+(u1.*xi)./2.0-u13.*xi.*2.0+(u25.*xi)./2.0+(W.*t4.*u7.*zeta)./4.0+(W.*t2.*u31.*zeta)./4.0+(W.*u7.*xi.*zeta)./4.0-W.*u19.*xi.*zeta+(W.*u31.*xi.*zeta)./4.0+(H.*eta.*t4.*u4)./4.0+(H.*eta.*t2.*u28)./4.0+(H.*eta.*u4.*xi)./4.0-H.*eta.*u16.*xi+(H.*eta.*u28.*xi)./4.0+(H.*W.*eta.*t4.*u10.*zeta)./8.0+(H.*W.*eta.*t2.*u34.*zeta)./8.0+(H.*W.*eta.*u10.*xi.*zeta)./8.0-(H.*W.*eta.*u22.*xi.*zeta)./2.0+(H.*W.*eta.*u34.*xi.*zeta)./8.0];
mt2 = [(t4.*u2)./2.0+(t2.*u26)./2.0+(u2.*xi)./2.0-u14.*xi.*2.0+(u26.*xi)./2.0+(W.*t4.*u8.*zeta)./4.0+(W.*t2.*u32.*zeta)./4.0+(W.*u8.*xi.*zeta)./4.0-W.*u20.*xi.*zeta+(W.*u32.*xi.*zeta)./4.0+(H.*eta.*t4.*u5)./4.0+(H.*eta.*t2.*u29)./4.0+(H.*eta.*u5.*xi)./4.0-H.*eta.*u17.*xi+(H.*eta.*u29.*xi)./4.0+(H.*W.*eta.*t4.*u11.*zeta)./8.0+(H.*W.*eta.*t2.*u35.*zeta)./8.0+(H.*W.*eta.*u11.*xi.*zeta)./8.0-(H.*W.*eta.*u23.*xi.*zeta)./2.0+(H.*W.*eta.*u35.*xi.*zeta)./8.0];
mt3 = [(t4.*u3)./2.0+(t2.*u27)./2.0+(u3.*xi)./2.0-u15.*xi.*2.0+(u27.*xi)./2.0+(W.*t4.*u9.*zeta)./4.0+(W.*t2.*u33.*zeta)./4.0+(W.*u9.*xi.*zeta)./4.0-W.*u21.*xi.*zeta+(W.*u33.*xi.*zeta)./4.0+(H.*eta.*t4.*u6)./4.0+(H.*eta.*t2.*u30)./4.0+(H.*eta.*u6.*xi)./4.0-H.*eta.*u18.*xi+(H.*eta.*u30.*xi)./4.0+(H.*W.*eta.*t4.*u12.*zeta)./8.0+(H.*W.*eta.*t2.*u36.*zeta)./8.0+(H.*W.*eta.*u12.*xi.*zeta)./8.0-(H.*W.*eta.*u24.*xi.*zeta)./2.0+(H.*W.*eta.*u36.*xi.*zeta)./8.0];
mt4 = [H.*t5.*u16.*(-1.0./2.0)+(H.*t4.*u4.*xi)./4.0+(H.*t2.*u28.*xi)./4.0-(H.*W.*t5.*u22.*zeta)./4.0+(H.*W.*t4.*u10.*xi.*zeta)./8.0+(H.*W.*t2.*u34.*xi.*zeta)./8.0,H.*t5.*u17.*(-1.0./2.0)+(H.*t4.*u5.*xi)./4.0+(H.*t2.*u29.*xi)./4.0-(H.*W.*t5.*u23.*zeta)./4.0+(H.*W.*t4.*u11.*xi.*zeta)./8.0+(H.*W.*t2.*u35.*xi.*zeta)./8.0,H.*t5.*u18.*(-1.0./2.0)+(H.*t4.*u6.*xi)./4.0+(H.*t2.*u30.*xi)./4.0-(H.*W.*t5.*u24.*zeta)./4.0+(H.*W.*t4.*u12.*xi.*zeta)./8.0+(H.*W.*t2.*u36.*xi.*zeta)./8.0];
mt5 = [W.*t5.*u19.*(-1.0./2.0)+(W.*t4.*u7.*xi)./4.0+(W.*t2.*u31.*xi)./4.0-(H.*W.*eta.*t5.*u22)./4.0+(H.*W.*eta.*t4.*u10.*xi)./8.0+(H.*W.*eta.*t2.*u34.*xi)./8.0,W.*t5.*u20.*(-1.0./2.0)+(W.*t4.*u8.*xi)./4.0+(W.*t2.*u32.*xi)./4.0-(H.*W.*eta.*t5.*u23)./4.0+(H.*W.*eta.*t4.*u11.*xi)./8.0+(H.*W.*eta.*t2.*u35.*xi)./8.0,W.*t5.*u21.*(-1.0./2.0)+(W.*t4.*u9.*xi)./4.0+(W.*t2.*u33.*xi)./4.0-(H.*W.*eta.*t5.*u24)./4.0+(H.*W.*eta.*t4.*u12.*xi)./8.0+(H.*W.*eta.*t2.*u36.*xi)./8.0];
nabla_u_xi = reshape([mt1,mt2,mt3,mt4,mt5],3,3);
end
